"""Backward-compatible public API for the former single-file module."""

from __future__ import annotations

from videotranslator.config import APP_DIAGNOSTIC_VERSION, BATCH_RECOVERY_SCHEMA_VERSION, BATCH_SIZE, DEFAULT_AUDIO_SETTINGS, DEFAULT_TARGET_LANGUAGE, EDGE_TTS_MAX_TIMEOUT_SEC, EDGE_TTS_MIN_TIMEOUT_SEC, EDGE_VOICE_PRESERVE_SEC, EDGE_VOICE_PROBE_INTERVAL_SEC, FINAL_ENCODE_MAX_TIMEOUT, FINAL_ENCODE_MIN_TIMEOUT, HEAVY_PAUSE_SYNC_COUNT, MASTER_LOUDNESS_I, MASTER_TRUE_PEAK, MAX_EMERGENCY_TEMPO, MAX_NATIVE_TTS_RATE, MAX_NATURAL_TEMPO, MIN_INSERTED_PAUSE, MIN_SYNC_GAP, MIN_TEMPO, MODELS_MAP, NETWORK_CONNECT_TIMEOUT_SEC, NETWORK_READ_TIMEOUT_SEC, NETWORK_STORM_RECOVERY_SUCCESSES, NETWORK_STORM_THRESHOLD, NETWORK_STORM_WINDOW_SEC, PAUSE_FINISH_MARGIN, PROBLEM_INDEX_SCHEMA_VERSION, PROBLEM_LOG_MAX_FILES, PROBLEM_LOG_RETENTION_DAYS, PROBLEM_LOG_SCHEMA_VERSION, PROBLEM_MANIFEST_SCHEMA_VERSION, PROBLEM_REPEAT_SAMPLE_EVENTS, PROBLEM_REPORT_REFRESH_SEC, PROBLEM_SESSION_STALE_SEC, SAMPLE_RATE, SETTINGS_LANGUAGE_VERSION, SPEECH_SPEED_LIMITS, TARGET_HEADROOM, TARGET_LANGUAGES, TOTAL_MAX_SPEECH_SPEED, TRANSLATION_BATCH_MAX_CHARS, TRANSLATION_BATCH_MAX_SEGMENTS, TRANSLATION_CHECKPOINT_EVERY, TRANSLATION_PROGRESS_EVERY, TTS_CACHE_MAX_BYTES, TTS_CACHE_ORPHAN_RETENTION_HOURS, TTS_CACHE_PREPARED_RETENTION_HOURS, TTS_CACHE_RECOVERY_RETENTION_DAYS, TTS_CACHE_SCHEMA_VERSION, TTS_CACHE_SIZE_CHECK_EVERY, TTS_CACHE_TARGET_BYTES, TTS_PREPARED_CACHE_SCHEMA_VERSION, TTS_PREPARE_WORKERS, VOICE_LIMIT, get_language_labels, get_target_language, get_target_language_by_code, get_voice_options, normalize_audio_settings
from videotranslator.core.cancel import CancelledError
from videotranslator.core.diagnostics import classify_exception, compact_exception, diagnostic_json_value, diagnostic_signature_value, exception_chain, redact_diagnostic_text, safe_log_filename, should_store_problem_occurrence
from videotranslator.core.io import atomic_write_json, atomic_write_text, read_json_file
from videotranslator.core.paths import get_logs_dir, get_problem_logs_dir, get_program_dir, get_translated_texts_dir, get_translation_checkpoints_dir, get_tts_cache_dir
from videotranslator.core.timefmt import fmt_time
from videotranslator.diagnostics.file_logger import FileLogger
from videotranslator.diagnostics.files import _is_owned_problem_session, archive_legacy_problem_logs, cleanup_old_problem_logs, find_previous_problem_summary, installed_package_versions, problem_log_relative_path, write_problem_logs_guide
from videotranslator.diagnostics.heartbeat import ActivityHeartbeat
from videotranslator.diagnostics.problem_logger import ProblemLogger
from videotranslator.media.audio import build_atempo_filter, calc_audio_work_timeout, calc_final_encode_timeout, ffmpeg_audio_ok, ffmpeg_has_encoder, ffmpeg_has_filter, final_video_encoder_attempts, get_audio_duration, master_voice_audio, polish_tts_audio, speed_audio, time_stretch_audio, trim_audio
from videotranslator.media.process import find_ffmpeg, find_ffprobe, format_subprocess_command, log_subprocess_result, run_subprocess
from videotranslator.media.video import assemble_final_video, extract_audio_for_whisper, get_media_duration, output_has_video_and_audio
from videotranslator.network.guard import NetworkStormGuard, ReusableGoogleTranslator, _SessionRequestsProxy
from videotranslator.network.http import edge_tts_timeout_for_text, install_requests_default_timeout, progressive_retry_delay
from videotranslator.pipeline.translator import VideoTranslator
from videotranslator.recovery.batch import batch_recovery_pending_entries, create_batch_recovery_state, get_batch_recovery_state_path, input_file_signature, load_batch_recovery_state, reconstruct_batch_recovery_state_from_problem_log, save_batch_recovery_state
from videotranslator.recovery.translation import load_translation_checkpoint, save_translation_checkpoint, translation_checkpoint_path, translation_segment_key
from videotranslator.reports.output import make_unique_output_path, write_translated_text_file, write_translation_report
from videotranslator.speech.whisper import get_whisper_model, is_cuda_available
from videotranslator.sync.pause import calc_quality_slot, edge_rate_from_speed, make_filter_script_for_pauses, merge_nearby_pause_plan, merge_short_segments, normalize_tts_text, sanitize_pause_plan
from videotranslator.translation.batching import build_translation_batch, parse_translation_batch, split_translation_batches
from videotranslator.tts.cache import TTSCache
from videotranslator.ui.app import App

__all__ = [
    'APP_DIAGNOSTIC_VERSION',
    'ActivityHeartbeat',
    'App',
    'BATCH_RECOVERY_SCHEMA_VERSION',
    'BATCH_SIZE',
    'CancelledError',
    'DEFAULT_AUDIO_SETTINGS',
    'DEFAULT_TARGET_LANGUAGE',
    'EDGE_TTS_MAX_TIMEOUT_SEC',
    'EDGE_TTS_MIN_TIMEOUT_SEC',
    'EDGE_VOICE_PRESERVE_SEC',
    'EDGE_VOICE_PROBE_INTERVAL_SEC',
    'FINAL_ENCODE_MAX_TIMEOUT',
    'FINAL_ENCODE_MIN_TIMEOUT',
    'FileLogger',
    'HEAVY_PAUSE_SYNC_COUNT',
    'MASTER_LOUDNESS_I',
    'MASTER_TRUE_PEAK',
    'MAX_EMERGENCY_TEMPO',
    'MAX_NATIVE_TTS_RATE',
    'MAX_NATURAL_TEMPO',
    'MIN_INSERTED_PAUSE',
    'MIN_SYNC_GAP',
    'MIN_TEMPO',
    'MODELS_MAP',
    'NETWORK_CONNECT_TIMEOUT_SEC',
    'NETWORK_READ_TIMEOUT_SEC',
    'NETWORK_STORM_RECOVERY_SUCCESSES',
    'NETWORK_STORM_THRESHOLD',
    'NETWORK_STORM_WINDOW_SEC',
    'NetworkStormGuard',
    'PAUSE_FINISH_MARGIN',
    'PROBLEM_INDEX_SCHEMA_VERSION',
    'PROBLEM_LOG_MAX_FILES',
    'PROBLEM_LOG_RETENTION_DAYS',
    'PROBLEM_LOG_SCHEMA_VERSION',
    'PROBLEM_MANIFEST_SCHEMA_VERSION',
    'PROBLEM_REPEAT_SAMPLE_EVENTS',
    'PROBLEM_REPORT_REFRESH_SEC',
    'PROBLEM_SESSION_STALE_SEC',
    'ProblemLogger',
    'ReusableGoogleTranslator',
    'SAMPLE_RATE',
    'SETTINGS_LANGUAGE_VERSION',
    'SPEECH_SPEED_LIMITS',
    'TARGET_HEADROOM',
    'TARGET_LANGUAGES',
    'TOTAL_MAX_SPEECH_SPEED',
    'TRANSLATION_BATCH_MAX_CHARS',
    'TRANSLATION_BATCH_MAX_SEGMENTS',
    'TRANSLATION_CHECKPOINT_EVERY',
    'TRANSLATION_PROGRESS_EVERY',
    'TTSCache',
    'TTS_CACHE_MAX_BYTES',
    'TTS_CACHE_ORPHAN_RETENTION_HOURS',
    'TTS_CACHE_PREPARED_RETENTION_HOURS',
    'TTS_CACHE_RECOVERY_RETENTION_DAYS',
    'TTS_CACHE_SCHEMA_VERSION',
    'TTS_CACHE_SIZE_CHECK_EVERY',
    'TTS_CACHE_TARGET_BYTES',
    'TTS_PREPARED_CACHE_SCHEMA_VERSION',
    'TTS_PREPARE_WORKERS',
    'VOICE_LIMIT',
    'VideoTranslator',
    '_SessionRequestsProxy',
    '_is_owned_problem_session',
    'archive_legacy_problem_logs',
    'assemble_final_video',
    'atomic_write_json',
    'atomic_write_text',
    'batch_recovery_pending_entries',
    'build_atempo_filter',
    'build_translation_batch',
    'calc_audio_work_timeout',
    'calc_final_encode_timeout',
    'calc_quality_slot',
    'classify_exception',
    'cleanup_old_problem_logs',
    'compact_exception',
    'create_batch_recovery_state',
    'diagnostic_json_value',
    'diagnostic_signature_value',
    'edge_rate_from_speed',
    'edge_tts_timeout_for_text',
    'exception_chain',
    'extract_audio_for_whisper',
    'ffmpeg_audio_ok',
    'ffmpeg_has_encoder',
    'ffmpeg_has_filter',
    'final_video_encoder_attempts',
    'find_ffmpeg',
    'find_ffprobe',
    'find_previous_problem_summary',
    'fmt_time',
    'format_subprocess_command',
    'get_audio_duration',
    'get_batch_recovery_state_path',
    'get_language_labels',
    'get_logs_dir',
    'get_media_duration',
    'get_problem_logs_dir',
    'get_program_dir',
    'get_target_language',
    'get_target_language_by_code',
    'get_translated_texts_dir',
    'get_translation_checkpoints_dir',
    'get_tts_cache_dir',
    'get_voice_options',
    'get_whisper_model',
    'input_file_signature',
    'install_requests_default_timeout',
    'installed_package_versions',
    'is_cuda_available',
    'load_batch_recovery_state',
    'load_translation_checkpoint',
    'log_subprocess_result',
    'make_filter_script_for_pauses',
    'make_unique_output_path',
    'master_voice_audio',
    'merge_nearby_pause_plan',
    'merge_short_segments',
    'normalize_audio_settings',
    'normalize_tts_text',
    'output_has_video_and_audio',
    'parse_translation_batch',
    'polish_tts_audio',
    'problem_log_relative_path',
    'progressive_retry_delay',
    'read_json_file',
    'reconstruct_batch_recovery_state_from_problem_log',
    'redact_diagnostic_text',
    'run_subprocess',
    'safe_log_filename',
    'sanitize_pause_plan',
    'save_batch_recovery_state',
    'save_translation_checkpoint',
    'should_store_problem_occurrence',
    'speed_audio',
    'split_translation_batches',
    'time_stretch_audio',
    'translation_checkpoint_path',
    'translation_segment_key',
    'trim_audio',
    'write_problem_logs_guide',
    'write_translated_text_file',
    'write_translation_report',
]
